name: Workflow Control Pipeline

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request_review:
    types: [submitted]

jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        id: unit-tests
        run: |
          echo "Running unit tests..."
          npm run test
        continue-on-error: true

      - name: Check test outcome
        id: test-result
        run: |
          if [ "${{ steps.unit-tests.outcome }}" == "failure" ]; then
            echo "tests_failed=true" >> $GITHUB_OUTPUT
          else
            echo "tests_failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify Commit Owner on Failure
        if: steps.test-result.outputs.tests_failed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const commit = context.sha;
            const actor = context.actor;
            const commitUrl = `https://github.com/${owner}/${repo}/commit/${commit}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: owner,
              repo: repo,
              body: `@${actor} The unit tests for your commit [${commit.substring(0, 7)}](${commitUrl}) have failed. Please check the [workflow run](${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}) for details.`
            });

      - name: Notify Reviewers on Success
        if: steps.test-result.outputs.tests_failed == 'false' && github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const pr = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${context.ref.replace('refs/heads/', '')}`
            });

            if (pr.data.length > 0) {
              const prNumber = pr.data[0].number;
              const reviewers = ['shaikhsahab07'];

              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner,
                repo,
                body: `✅ All tests have passed! @${reviewers.join(' @')}, please review this PR.`
              });

              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: prNumber,
                reviewers
              });
            } else {
              console.log('No open PR found for this branch.');
            }
