name: Download artifact reusable workflow
on: 
 workflow_call:
   inputs:
     artifact-name:
       description: This would be the name of artifact which we are uploading
       type: string
       required: true
jobs:
 download:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        id: download-confirmation
        uses: actions/download-artifact@v3 
        with:
          name: ${{ inputs.artifact-name }}
      - name: verify download artifact step
        if: ${{ failure() && steps.download-confirmation.outcome == 'failure' }}
        run: echo 'Error Reusable workflow got failed'

